; generated by BambuStudio 02.05.00.66
; filament_diameter = 1.75
; filament_density = 1.24
G90
M83
; CHANGE_LAYER
; Z_HEIGHT: 0.2
; LAYER_HEIGHT: 0.2
; LINE_WIDTH: 0.42
; FEATURE: Inner wall
G1 X0 Y0 Z0.2
G1 X10 Y0 E1
G1 X10 Y10 E1
