; generated by BambuStudio 02.05.00.66
; filament_diameter = 1.75
; filament_density = 1.24
; filament_type = PLA
; filament_colour = #00FF00
G90
M83
T0
; CHANGE_LAYER
; Z_HEIGHT: 0.2
; LAYER_HEIGHT: 0.2
; LINE_WIDTH: 0.5
; FEATURE: Support
G1 X0 Y0 Z0.2
G1 X10 Y0 E1
; FEATURE: Support transition
G1 X10 Y10 E0.5
; CHANGE_LAYER
; Z_HEIGHT: 0.4
; FEATURE: Support interface
G1 X0 Y10 Z0.4 E0.5
; FEATURE: Inner wall
G1 X0 Y0 E1
