; generated by BambuStudio 02.05.00.66
; filament_diameter = 1.75
; filament_density = 1.24
G90
M83
; CHANGE_LAYER
; LINE_WIDTH: 0.5
; LAYER_HEIGHT: 0.2
; FEATURE: Support
G1 X0 Y0 Z0.2
G1 X5 Y5 E0.7
; FEATURE: Support interface
G1 X10 Y5 E0.3
